# Nombre del Workflow
name: 🚀 Importar Tareas desde JSON

# Disparador
on:
  workflow_dispatch:

# Permisos:
# Necesitamos permisos para leer contenido, escribir issues Y ESCRIBIR ETIQUETAS
permissions:
  contents: read
  issues: write
  labels: write # <-- NUEVO: Permiso para crear etiquetas

jobs:
  import-tasks:
    runs-on: ubuntu-latest
    steps:
      # 1. Clona el repositorio para poder leer el archivo tasks.json
      - name: Checkout del código
        uses: actions/checkout@v4

      # 2. Lee el JSON, itera sobre cada tarea y crea un issue
      - name: Crear Issues desde JSON
        run: |
          PROJECT_URL="${{ secrets.PROJECT_URL }}"
          JSON_FILE="tasks.json"

          echo "Iniciando la importación de tareas desde $JSON_FILE..."
          echo "Añadiendo a Proyecto: $PROJECT_URL"

          jq -c '.[]' $JSON_FILE | while read task; do
            
            # --- INICIO: NUEVO BLOQUE PARA CREAR ETIQUETAS ---
            echo "Verificando etiquetas..."
            
            # Itera sobre cada etiqueta en el array 'labels' del JSON
            echo $task | jq -r '.labels[]' | while read label; do
              if [ -n "$label" ]; then # Asegura que la etiqueta no esté vacía
                echo "Asegurando que la etiqueta '$label' exista..."
                
                # Intenta crear la etiqueta.
                # Si ya existe, el comando fallará, pero `|| true` 
                # captura el error y permite que el script continúe.
                gh label create "$label" --color "f29513" --description "Etiqueta autogenerada por importación" || true
              fi
            done
            # --- FIN: NUEVO BLOQUE PARA CREAR ETIQUETAS ---

            # Extrae los datos de la tarea (como antes)
            TITLE=$(echo $task | jq -r '.title')
            BODY=$(echo $task | jq -r '.description')
            LABELS=$(echo $task | jq -r '.labels | join(",")')

            echo "Creando tarea: $TITLE"

            # Crea el issue (como antes)
            # Ahora estamos seguros de que las etiquetas existen
            gh issue create --title "$TITLE" \
                            --body "$BODY" \
                            --label "$LABELS" \
                            --project "$PROJECT_URL"
          
          done
          
          echo "✅ Importación completada."

        # Autenticación (como antes)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
